AWSTemplateFormatVersion: 2010-09-09

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "Project Name Prefix"
        Parameters:
          - PJPrefix

Parameters:
  PJPrefix:
    Type: String


Resources:   
  SGForALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags: 
        - Key: Name
          Value: ALB-SG
      GroupName: ALB-SG
      GroupDescription: Allow http to client host
      VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  
  SGForWebserver:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags: 
        - Key: Name
          Value: Webserver-SG
      GroupName: Webserver-SG
      GroupDescription: Allow http to client host
      VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
      # インバウンド設定
      SecurityGroupIngress:
        - FromPort: 80
          IpProtocol: tcp
          ToPort: 80
          SourceSecurityGroupId: !Ref SGForALB
        - FromPort: 22
          IpProtocol: tcp
          ToPort: 22
          CidrIp: 0.0.0.0/0

  SGForRDS:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: { "Fn::ImportValue": !Sub "${PJPrefix}-vpc" }
      GroupName: RDS-SG
      GroupDescription: "-"
      Tags:
        - Key: Name
          Value: RDS-SG

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref SGForWebserver
          

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#                
Outputs:
#SecurityGroup
  SGForALB:
    Value: !Ref SGForALB
    Export:
      Name: !Sub "${PJPrefix}-alb-sg"
  
  SGForWebserver:
    Value: !Ref SGForWebserver
    Export:
      Name: !Sub "${PJPrefix}-webserver-sg"

  SGForRDS:
    Value: !Ref SGForRDS
    Export:
      Name: !Sub "${PJPrefix}-rds-sg"